### PR TITLE
libsql/core: Fix Statement::execute() signature

### LINKED ISSUE #246: Fix Statement::execute() to return number of changed rows
The `execute()` function signature is wrong:

```rust
pub fn execute(&self, params: &Params) -> Option<Rows> {
```

it should be:

```rust
pub fn raw_execute(&mut self) -> Result<usize> {
```

like in rusqlite.

### PR DESCRIPTION
**Pull request by penberg**
The JavaScript language bindings, for example, need a function for executing a SQL statement and getting the number of changed rows back. The rusqlite `execute()` function does just that so let's fix our function signature to be compatible.

Fixes #246

### CODE REVIEW

File: crates/core/src/statement.rs [hunk 1]
```diff
@@ -92,16 +91,12 @@ impl Statement {
...
         let err = self.inner.step();
         match err as u32 {
-            crate::ffi::SQLITE_OK => None,
-            crate::ffi::SQLITE_DONE => None,
-            _ => Some(Rows {
-                stmt: self.inner.clone(),
-                err: RefCell::new(Some(err)),
-            }),
+            crate::ffi::SQLITE_DONE => Ok(self.conn.changes()),
+            _ => todo!(), // FIXME
```
Comment (psarna) [inline crates/core/src/statement.rs:99]: doesn't it just boil down to `e => Err(libsql_sys::Error::LibError(e))`?

**Review by haaawk — APPROVED** [review]
